### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by ericfreese**
Rewriting a lot of code for improved stability.

- Using POSTDISPLAY instead of LBUFFER and RBUFFER.
- Removing pause/suspend/resume state management code.
- Removing unused server/client code.

See issue #86.

## TODO

- [ ] Remove suggestion (POSTDISPLAY) on ctrl-c. [Not sure how to do this. Ideas?]
- [x] Fix syntax highlight coloring.
- [ ] Display suggestion again after navigating history.
    - After pressing up and then down, should display the same autosuggestion it originally did.
- [x] Multi-line support
- [x] support for overriding user-defined widgets (like history-substring-search-up/down)

### CODE REVIEW

**Comment by faceleg** [comment]
Such wow

**Comment by faceleg** [comment]
@tarruda can @ericfreese please have collaborator access?

**Comment by tarruda** [comment]
@ericfreese added as collaborator, thanks for the contributions

**Comment by faceleg** [comment]
Thank you @tarruda! And thanks for neovim :) been using it daily for many many months.

**Comment by ericfreese** [comment]
Thanks @tarruda

It's in a pretty stable place now with syntax highlighting working. Would be great if you could pull it down and play around with it. I'm going to be out of town through the end of the weekend, but should be able to get back to this next week.

**Comment by faceleg** [comment]
I'll install it and report back if anything goes crazy

**Comment by ericfreese** [comment]
I'd like to go ahead and merge this into master. It's looking pretty solid to me. Any objections?

I was planning to keep the current master branch available via a separate branch so people can always use the current version if necessary.

**Comment by ericfreese** [comment]
Closed. See PR #91.

**Pull request closed without merging**
