### PR TITLE
Support OMZ

### PR DESCRIPTION
**Pull request by a-x-**
Add symlink for OMZ compatibility

### CODE REVIEW

**Comment by jirutka** [comment]
-1, please create symlink instead of renaming the file. OMZ isn't the only -"modules manager" and others may have different conventions.

**Comment by faceleg** [comment]
Thanks for the review @jirutka

**Comment by a-x-** [comment]
This is cool idea! :)

**Comment by a-x-** [comment]
done

**Comment by faceleg** [comment]
@jirutka OK to merge?

**Comment by jirutka** [comment]
:shipit:

**Comment by faceleg** [comment]
Had to hover the image to realise it was "shipit", lol

**Pull request merged**
